[package]
name = "http_metal"
version = "0.0.1"
authors = ["lucas"]
description = "A fast and simple HTTP server framework for Rust - In Development -"
license = "MIT/Apache-2.0"

[dependencies]
regex = "1"